version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - REACT_APP_FIREBASE_API_KEY=AIzaSyATx6fcoqiPoh2clwBeabeQ6r4a6DG6G9s
      - REACT_APP_FIREBASE_AUTH_DOMAIN=tidewatch-4bb07.firebaseapp.com
      - REACT_APP_FIREBASE_DATABASE_URL=https://tidewatch-4bb07.firebaseio.com
      - REACT_APP_FIREBASE_PROJECT_ID=tidewatch-4bb07
      - REACT_APP_FIREBASE_STORAGE_BUCKET=tidewatch-4bb07.appspot.com
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=293414242238
      - REACT_APP_FIREBASE_APP_ID=1:293414242238:android:aad978b76c4a3fcf771bef
    command: /bin/sh -c "while true; do sleep 1; done"
    stdin_open: true
    tty: true